export const experienceCopy = {
  en: {
    issue: "A fresh perspective on growing",
    heroFirst: "Good things",
    heroSecond: "start small.",
    heroText:
      "A seed. A little possibility. A whole new season. Discover Hazera seeds with Greensoff, your local connection in Uzbekistan.",
    seedLabel: "A small beginning",
    scatter: "Sow the seeds",
    gather: "Bring them together",
    sculpture: "Interactive seed sculpture",
    seedHint: "Move to explore. Press to sow.",
    seedFallback: "An arrangement of golden seeds",
    strip: [
      "Small beginnings",
      "Hazera seeds",
      "Local connections",
      "Uzbekistan",
    ],
    introLabel: "01 — A DIFFERENT KIND OF CONNECTION",
    introTitle: "Big possibilities.\nA little closer.",
    introText:
      "We bring Hazera seeds to growers through our shops in Uzbekistan. International seed expertise, with a local place to start.",
    packetTop: "THE START OF SOMETHING",
    packetBottom: "YOUR NEXT SEASON",
    seedTitle: "Seeds, with\npossibility inside.",
    seedText:
      "Explore Hazera’s seed range through Greensoff. Talk to our shops about available varieties, pack sizes and your next season.",
    seedNote: "Discover the range. Confirm local availability.",
    journeyLabel: "02 — THINKING A SEASON AHEAD",
    journeyTitle: "One small choice.\nA whole journey.",
    journeyHint: "Explore the three steps",
    steps: [
      {
        title: "Choose.",
        subtitle: "Start with the seed",
        text: "Explore the available Hazera range. Your crop, growing conditions and season help shape your choice.",
        visual: "A beginning full of possibility",
      },
      {
        title: "Prepare.",
        subtitle: "Make room for growth",
        text: "Think about your growing medium, water and the season ahead. A considered beginning makes planning easier.",
        visual: "Every row starts with a plan",
      },
      {
        title: "Connect.",
        subtitle: "Keep it local",
        text: "Visit Greensoff’s shops in Uzbekistan to discuss seed varieties, pack sizes and current availability.",
        visual: "Global seeds. Local connections.",
      },
    ],
    partnerLabel: "03 — GREENSOFF × HAZERA",
    partnerTitle: "A shared belief\nin the next season.",
    partnerText:
      "Hazera is the seed brand at the heart of Greensoff. We connect its vegetable seed expertise with growers in Uzbekistan.",
    shopLabel: "04 — YOUR LOCAL STARTING POINT",
    shopTitle: "Good seeds.\nGood neighbours.",
    shopText:
      "Find your connection to Hazera seeds through the Greensoff shop network in Uzbekistan.",
    shopTag: "Seed shops · Uzbekistan",
    shopWindow: "A new season starts here",
    shopNote: "Shop addresses and opening hours are coming soon.",
    footerLine: "Here’s to what comes next.",
    motion: "Animation",
  },
  ru: {
    issue: "Свежий взгляд на новый сезон",
    heroFirst: "Большое",
    heroSecond: "начинается с малого.",
    heroText:
      "Семя. Возможность. Новый сезон. Откройте семена Hazera с Greensoff — вашей местной сетью магазинов в Узбекистане.",
    seedLabel: "Маленькое начало",
    scatter: "Посеять семена",
    gather: "Собрать вместе",
    sculpture: "Интерактивная композиция из семян",
    seedHint: "Двигайте курсор. Нажмите, чтобы посеять.",
    seedFallback: "Композиция из золотистых семян",
    strip: ["Маленькое начало", "Семена Hazera", "Местные связи", "Узбекистан"],
    introLabel: "01 — БЛИЖЕ К ВАШЕМУ ХОЗЯЙСТВУ",
    introTitle: "Большие возможности.\nСовсем рядом.",
    introText:
      "Мы делаем семена Hazera доступнее для аграриев через наши магазины в Узбекистане. Мировой опыт в семенах и местная точка отсчёта.",
    packetTop: "НАЧАЛО ЧЕГО-ТО БОЛЬШЕГО",
    packetBottom: "ВАШ НОВЫЙ СЕЗОН",
    seedTitle: "Семена.\nВозможности внутри.",
    seedText:
      "Познакомьтесь с ассортиментом Hazera в Greensoff. Уточните доступные сорта и фасовку и обсудите планы на сезон в наших магазинах.",
    seedNote: "Изучите ассортимент. Уточните наличие.",
    journeyLabel: "02 — ДУМАЯ О НОВОМ СЕЗОНЕ",
    journeyTitle: "Маленький выбор.\nБольшой путь.",
    journeyHint: "Откройте три шага",
    steps: [
      {
        title: "Выбирайте.",
        subtitle: "Начните с семян",
        text: "Изучите доступные семена Hazera. Культура, условия выращивания и сезон помогут сделать выбор.",
        visual: "Начало, полное возможностей",
      },
      {
        title: "Готовьтесь.",
        subtitle: "Создайте условия для роста",
        text: "Подумайте о почве, воде и предстоящем сезоне. Продуманное начало помогает планировать.",
        visual: "Каждый ряд начинается с плана",
      },
      {
        title: "Приходите.",
        subtitle: "Мы рядом",
        text: "Посетите магазины Greensoff в Узбекистане, чтобы обсудить сорта семян, фасовку и текущее наличие.",
        visual: "Мировые семена. Местные связи.",
      },
    ],
    partnerLabel: "03 — GREENSOFF × HAZERA",
    partnerTitle: "Общая вера\nв новый сезон.",
    partnerText:
      "Hazera — бренд семян в основе Greensoff. Мы соединяем опыт Hazera в овощных культурах с аграриями Узбекистана.",
    shopLabel: "04 — ВАША МЕСТНАЯ ТОЧКА ОТСЧЁТА",
    shopTitle: "Хорошие семена.\nДобрые соседи.",
    shopText:
      "Откройте семена Hazera через сеть магазинов Greensoff в Узбекистане.",
    shopTag: "Магазины семян · Узбекистан",
    shopWindow: "Новый сезон начинается здесь",
    shopNote: "Адреса магазинов и часы работы скоро появятся здесь.",
    footerLine: "Навстречу новому сезону.",
    motion: "Анимация",
  },
};
