// Greensoff editorial content. Keep English and Russian keys in sync.
export const siteCopy = {
  "en": {
    "solutions": "Our seeds",
    "story": "About Greensoff",
    "partners": "Hazera",
    "contact": "Our shops",
    "eyebrow": "HAZERA SEEDS. CLOSER TO YOU.",
    "title": "Small seeds.",
    "accent": "Greener beginnings.",
    "intro": "Greensoff brings Hazera seeds closer to growers through a network of shops in Uzbekistan. Your next season starts here.",
    "explore": "Explore Hazera seeds",
    "discover": "Meet Greensoff",
    "scroll": "SCROLL TO EXPLORE",
    "since": "HAZERA SEED DISTRIBUTOR · UZBEKISTAN",
    "pause": "Pause motion",
    "play": "Resume motion",
    "trusted": "GLOBAL SEED EXPERTISE. LOCAL CONNECTIONS.",
    "solutionEyebrow": "01 / FROM SEED TO SEASON",
    "solutionTitle": "Your next harvest\nbegins with a choice.",
    "solutionIntro": "Discover Hazera seeds, get to know Greensoff and connect with our shops in Uzbekistan.",
    "categories": [
      {
        "id": "seeds",
        "label": "Hazera seeds",
        "description": "Explore seeds from Hazera for your next growing season.",
        "detail": "Greensoff distributes Hazera seeds in Uzbekistan. Ask at our shops about available varieties and pack sizes.",
        "tag": "THE BEGINNING",
        "brands": "Hazera",
        "href": "/products"
      },
      {
        "id": "shops",
        "label": "Our shops",
        "description": "A local connection to Hazera seeds through Greensoff shops in Uzbekistan.",
        "tag": "CLOSER TO YOU",
        "brands": "Greensoff · Uzbekistan",
        "href": "/#shops"
      },
      {
        "id": "about",
        "label": "Meet Greensoff",
        "description": "Discover the seed distributor connecting Hazera with growers in Uzbekistan.",
        "tag": "OUR CONNECTION",
        "brands": "Greensoff × Hazera",
        "href": "/#about"
      }
    ],
    "elementEyebrow": "02 / A CONNECTED APPROACH",
    "elementTitle": "Small elements.\nExtraordinary possibilities.",
    "elementIntro": "A seed is only the beginning. Explore three essentials of cultivation: soil, water and nutrition.",
    "elementLabels": [
      "Soil",
      "Water",
      "Nutrition"
    ],
    "elementDescriptions": [
      "A suitable growing medium is the foundation of cultivation. Consider your soil and growing conditions when choosing seeds.",
      "Water management is part of every growing season. Plan irrigation around your crop and local conditions.",
      "Nutrition supports plant development. Consider the requirements of your crop throughout the season."
    ],
    "interactive": "DRAG TO ROTATE",
    "scene": "Agricultural model",
    "modelNames": [
      "Cultivated soil profile",
      "Drip irrigation assembly",
      "Granular fertilizer"
    ],
    "modelControls": "Model view controls",
    "rotateLeft": "Rotate left",
    "rotateRight": "Rotate right",
    "zoomIn": "Zoom in",
    "zoomOut": "Zoom out",
    "resetView": "Reset view",
    "aboutEyebrow": "03 / MEET GREENSOFF",
    "aboutTitle": "A world of seeds.\nA local connection.",
    "aboutIntro": "Greensoff is a distributor of Hazera seeds with a network of shops in Uzbekistan.",
    "aboutBody": "We connect growers with Hazera seeds through local retail. Whether you are preparing for a new season or exploring your seed options, our shops are a place to begin.",
    "team": "Our home market",
    "established": "Seed brand we distribute",
    "network": "Shops in Uzbekistan",
    "direct": "Distributor of Hazera seeds",
    "partnerEyebrow": "04 / OUR SEED BRAND",
    "partnerTitle": "Hazera seeds.\nGreensoff connections.",
    "partnerIntro": "Explore the seed brand at the heart of Greensoff. Hazera vegetable seed expertise, connected with growers in Uzbekistan.",
    "contactEyebrow": "05 / STAY CONNECTED",
    "contactTitle": "A new season.\nStay in the know.",
    "contactIntro": "Leave your email for Greensoff seed and shop updates.",
    "email": "Your email address",
    "subscribe": "Keep me informed",
    "submitting": "Subscribing…",
    "privacy": "Your email will be used for Greensoff updates.",
    "address": "Uzbekistan",
    "street": "Hazera seed distributor · Retail shop network",
    "footerLine": "Seeds of possibility. Closer to you.",
    "catalogue": "Find your next beginning.",
    "catalogueIntro": "Discover Hazera seeds through Greensoff. Ask at our shops about the current range, varieties and availability.",
    "all": "Seed range",
    "back": "Back to home",
    "details": "Product information",
    "close": "Close details",
    "enquire": "Visit our shops",
    "available": "Varieties and stock vary. Confirm availability at a Greensoff shop before planning your order.",
    "cropNames": [
      "Hazera seeds"
    ],
    "skip": "Skip to content",
    "menu": "Navigation menu",
    "more": "Explore Hazera seeds",
    "shopsEyebrow": "05 / GREENSOFF NEAR YOU",
    "shopsTitle": "Rooted in Uzbekistan.\nConnected through our shops.",
    "shopsIntro": "Our shop network brings Hazera seeds closer to growers in Uzbekistan.",
    "shopsNote": "Shop addresses and opening hours will be published here.",
    "shopsCta": "Explore the seed range",
    "landscapeNote": "SEEDS. SEASONS. POSSIBILITIES."
  },
  "ru": {
    "solutions": "Наши семена",
    "story": "О Greensoff",
    "partners": "Hazera",
    "contact": "Наши магазины",
    "eyebrow": "СЕМЕНА HAZERA. БЛИЖЕ К ВАМ.",
    "title": "Маленькие семена.",
    "accent": "Большое начало.",
    "intro": "Greensoff делает семена Hazera ближе к аграриям через сеть магазинов в Узбекистане. Ваш новый сезон начинается здесь.",
    "explore": "Открыть семена Hazera",
    "discover": "Знакомьтесь: Greensoff",
    "scroll": "ЛИСТАЙТЕ И ОТКРЫВАЙТЕ",
    "since": "ДИСТРИБЬЮТОР СЕМЯН HAZERA · УЗБЕКИСТАН",
    "pause": "Остановить анимацию",
    "play": "Включить анимацию",
    "trusted": "МИРОВОЙ ОПЫТ В СЕМЕНАХ. МЕСТНЫЕ СВЯЗИ.",
    "solutionEyebrow": "01 / ОТ СЕМЯН К НОВОМУ СЕЗОНУ",
    "solutionTitle": "Ваш следующий урожай\nначинается с выбора.",
    "solutionIntro": "Откройте семена Hazera, познакомьтесь с Greensoff и нашей сетью магазинов в Узбекистане.",
    "categories": [
      {
        "id": "seeds",
        "label": "Семена Hazera",
        "description": "Откройте семена Hazera для нового сезона выращивания.",
        "detail": "Greensoff — дистрибьютор семян Hazera в Узбекистане. Уточняйте доступные сорта и фасовку в наших магазинах.",
        "tag": "НАЧАЛО",
        "brands": "Hazera",
        "href": "/products"
      },
      {
        "id": "shops",
        "label": "Наши магазины",
        "description": "Семена Hazera ближе к вам — в магазинах Greensoff в Узбекистане.",
        "tag": "БЛИЖЕ К ВАМ",
        "brands": "Greensoff · Узбекистан",
        "href": "/#shops"
      },
      {
        "id": "about",
        "label": "О Greensoff",
        "description": "Познакомьтесь с дистрибьютором семян, соединяющим Hazera с аграриями Узбекистана.",
        "tag": "НАШИ СВЯЗИ",
        "brands": "Greensoff × Hazera",
        "href": "/#about"
      }
    ],
    "elementEyebrow": "02 / КОМПЛЕКСНЫЙ ПОДХОД",
    "elementTitle": "Малые элементы.\nБольшие возможности.",
    "elementIntro": "Семена — только начало. Откройте три основы выращивания: почву, воду и питание.",
    "elementLabels": [
      "Почва",
      "Вода",
      "Питание"
    ],
    "elementDescriptions": [
      "Подходящая среда для роста — основа выращивания. При выборе семян учитывайте почву и условия вашего хозяйства.",
      "Управление водой — часть каждого сезона. Планируйте орошение с учётом культуры и местных условий.",
      "Питание поддерживает развитие растений. Учитывайте потребности вашей культуры на протяжении сезона."
    ],
    "interactive": "ПЕРЕТАЩИТЕ ДЛЯ ВРАЩЕНИЯ",
    "scene": "Сельскохозяйственная модель",
    "modelNames": [
      "Разрез обработанной почвы",
      "Узел капельного орошения",
      "Гранулированное удобрение"
    ],
    "modelControls": "Управление видом модели",
    "rotateLeft": "Повернуть влево",
    "rotateRight": "Повернуть вправо",
    "zoomIn": "Приблизить",
    "zoomOut": "Отдалить",
    "resetView": "Сбросить вид",
    "aboutEyebrow": "03 / ЗНАКОМЬТЕСЬ: GREENSOFF",
    "aboutTitle": "Мир семян.\nБлиже к вам.",
    "aboutIntro": "Greensoff — дистрибьютор семян Hazera с сетью магазинов в Узбекистане.",
    "aboutBody": "Мы знакомим аграриев с семенами Hazera через местные магазины. Готовитесь к новому сезону или изучаете ассортимент семян? Начните с Greensoff.",
    "team": "Наша страна",
    "established": "Бренд семян, который мы представляем",
    "network": "Магазины в Узбекистане",
    "direct": "Дистрибьютор семян Hazera",
    "partnerEyebrow": "04 / НАШ БРЕНД СЕМЯН",
    "partnerTitle": "Семена Hazera.\nРядом с Greensoff.",
    "partnerIntro": "Познакомьтесь с брендом семян в основе Greensoff. Опыт Hazera в овощных культурах — ближе к аграриям Узбекистана.",
    "contactEyebrow": "05 / БУДЬТЕ НА СВЯЗИ",
    "contactTitle": "Новый сезон.\nСвежие новости.",
    "contactIntro": "Оставьте электронную почту для новостей о семенах и магазинах Greensoff.",
    "email": "Ваш email",
    "subscribe": "Быть в курсе",
    "submitting": "Подписываем…",
    "privacy": "Ваш email будет использоваться для новостей Greensoff.",
    "address": "Узбекистан",
    "street": "Дистрибьютор семян Hazera · Сеть магазинов",
    "footerLine": "Возможности в каждом семени. Ближе к вам.",
    "catalogue": "Найдите своё новое начало.",
    "catalogueIntro": "Откройте семена Hazera с Greensoff. Уточняйте ассортимент, сорта и наличие в наших магазинах.",
    "all": "Ассортимент семян",
    "back": "На главную",
    "details": "О продукции",
    "close": "Закрыть подробности",
    "enquire": "Наши магазины",
    "available": "Ассортимент и наличие меняются. Перед заказом уточните информацию в магазине Greensoff.",
    "cropNames": [
      "Семена Hazera"
    ],
    "skip": "Перейти к содержимому",
    "menu": "Меню навигации",
    "more": "Открыть семена Hazera",
    "shopsEyebrow": "05 / GREENSOFF РЯДОМ",
    "shopsTitle": "Наши корни — в Узбекистане.\nНаши связи — через магазины.",
    "shopsIntro": "Наша сеть магазинов делает семена Hazera ближе к аграриям Узбекистана.",
    "shopsNote": "Адреса магазинов и часы работы появятся здесь.",
    "shopsCta": "Посмотреть семена",
    "landscapeNote": "СЕМЕНА. СЕЗОНЫ. ВОЗМОЖНОСТИ."
  }
};
export const partners = [{name:"Hazera",logo:"/partners/hazera.svg",key:"Hazera"}];
